import type { Property } from "@/types";
import { ListingType, PropertyStatus, NegotiationStatus } from "@/types/enums";

export const properties: Property[] = [
  {
    id: "prop-001",
    slug: "3-bedroom-duplex-lekki",
    title: "3-Bedroom Duplex",
    description: "A beautifully finished 3-bedroom duplex in a secured estate in Lekki Phase 1.",
    listingType: ListingType.SALE,
    status: PropertyStatus.AVAILABLE,
    negotiationStatus: NegotiationStatus.NEGOTIABLE,
    isFeatured: true,
    isPinned: false,
    city: "Lekki",
    state: "Lagos",
    country: "Nigeria",
    createdAt: new Date("2026-06-01"),
    updatedAt: new Date("2026-06-01"),
    location: "Lekki Phase 1, Lagos",
    price: "₦45,000,000",
    type: "House",
    bedrooms: 3,
    bathrooms: 3,
    size: "280 sqm",
    image: "/images/properties/prop-001.svg",
    featured: true,
    whatsappMessage:
      "Hi, I'm interested in the 3-Bedroom Duplex in Lekki Phase 1 listed on your website."
  },
  {
    id: "prop-002",
    slug: "modern-apartment-vi",
    title: "Modern Apartment",
    description: "Luxury 2-bedroom apartment with ocean view in the heart of Victoria Island.",
    listingType: ListingType.SALE,
    status: PropertyStatus.AVAILABLE,
    negotiationStatus: NegotiationStatus.NEGOTIABLE,
    isFeatured: true,
    isPinned: false,
    city: "Victoria Island",
    state: "Lagos",
    country: "Nigeria",
    createdAt: new Date("2026-06-01"),
    updatedAt: new Date("2026-06-01"),
    location: "Victoria Island, Lagos",
    price: "₦35,000,000",
    type: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    size: "150 sqm",
    image: "/images/properties/prop-002.svg",
    featured: true,
    whatsappMessage:
      "Hi, I'm interested in the Modern Apartment in Victoria Island listed on your website."
  },
  {
    id: "prop-003",
    slug: "commercial-space-ikoyi",
    title: "Commercial Space",
    description: "Prime commercial space ideal for office or retail in the upscale Ikoyi area.",
    listingType: ListingType.SALE,
    status: PropertyStatus.AVAILABLE,
    negotiationStatus: NegotiationStatus.NEGOTIABLE,
    isFeatured: true,
    isPinned: false,
    city: "Ikoyi",
    state: "Lagos",
    country: "Nigeria",
    createdAt: new Date("2026-06-01"),
    updatedAt: new Date("2026-06-01"),
    location: "Ikoyi, Lagos",
    price: "₦60,000,000",
    type: "Commercial",
    size: "500 sqm",
    image: "/images/properties/prop-003.svg",
    featured: true,
    whatsappMessage:
      "Hi, I'm interested in the Commercial Space in Ikoyi listed on your website."
  },
  {
    id: "prop-004",
    slug: "residential-land-ajah",
    title: "Residential Land",
    description: "Residential land in a developing area with excellent investment potential.",
    listingType: ListingType.LAND,
    status: PropertyStatus.AVAILABLE,
    negotiationStatus: NegotiationStatus.NEGOTIABLE,
    isFeatured: false,
    isPinned: false,
    city: "Ajah",
    state: "Lagos",
    country: "Nigeria",
    createdAt: new Date("2026-06-01"),
    updatedAt: new Date("2026-06-01"),
    location: "Ajah, Lagos",
    price: "₦12,000,000",
    type: "Land",
    size: "800 sqm",
    image: "/images/properties/prop-004.svg",
    featured: false,
    whatsappMessage:
      "Hi, I'm interested in the Residential Land in Ajah listed on your website."
  },
  {
    id: "prop-005",
    slug: "4-bedroom-mansion-banana-island",
    title: "4-Bedroom Mansion",
    description: "Exclusive 4-bedroom mansion on prestigious Banana Island with private beach access.",
    listingType: ListingType.SALE,
    status: PropertyStatus.AVAILABLE,
    negotiationStatus: NegotiationStatus.NEGOTIABLE,
    isFeatured: false,
    isPinned: false,
    city: "Banana Island",
    state: "Lagos",
    country: "Nigeria",
    createdAt: new Date("2026-06-01"),
    updatedAt: new Date("2026-06-01"),
    location: "Banana Island, Lagos",
    price: "₦150,000,000",
    type: "House",
    bedrooms: 4,
    bathrooms: 4,
    size: "450 sqm",
    image: "/images/properties/prop-005.svg",
    featured: false,
    whatsappMessage:
      "Hi, I'm interested in the 4-Bedroom Mansion on Banana Island listed on your website."
  },
  {
    id: "prop-006",
    slug: "studio-apartment-yaba",
    title: "Studio Apartment",
    description: "Compact studio apartment perfect for young professionals or students.",
    listingType: ListingType.SALE,
    status: PropertyStatus.AVAILABLE,
    negotiationStatus: NegotiationStatus.NEGOTIABLE,
    isFeatured: false,
    isPinned: false,
    city: "Yaba",
    state: "Lagos",
    country: "Nigeria",
    createdAt: new Date("2026-06-01"),
    updatedAt: new Date("2026-06-01"),
    location: "Yaba, Lagos",
    price: "₦8,000,000",
    type: "Apartment",
    bedrooms: 1,
    bathrooms: 1,
    size: "50 sqm",
    image: "/images/properties/prop-006.svg",
    featured: false,
    whatsappMessage:
      "Hi, I'm interested in the Studio Apartment in Yaba listed on your website."
  }
];
